packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

# Catalog for shared dependencies
catalog:
  # React ecosystem
  react: ^19.0.0
  react-dom: ^19.0.0
  next: 15.3.5
  
  # TypeScript
  typescript: ^5.3.3
  '@types/node': ^20.10.5
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  
  # Backend
  express: ^4.18.2
  '@types/express': ^4.17.21
  
  # Database
  '@prisma/client': ^5.7.1
  prisma: ^5.7.1
  
  # Validation
  zod: ^3.22.4
  
  # Utilities
  lodash: ^4.17.21
  '@types/lodash': ^4.14.202
  
  # Testing
  jest: ^29.7.0
  '@types/jest': ^29.5.8
  
  # Linting & Formatting
  eslint: ^8.56.0
  prettier: ^3.1.1
  
  # Build tools
  turbo: ^1.11.2
